{% set name = "ruff-lsp" %}
{% set version = "0.0.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ruff_lsp-{{ version }}.tar.gz
  sha256: efc0381d43e34aef4b5fdecd6c84f8a1f3a52aa2c0cb2a4d73bb4b7075095e93

build:
  entry_points:
    - ruff-lsp = ruff_lsp.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - packaging >=23.1
    - pygls >=1.1.0
    - lsprotocol >=2023.0.0a1
    - ruff >=0.0.274
    - typing-extensions

test:
  imports:
    - ruff_lsp
  commands:
    - pip check
    - ruff-lsp --help
  requires:
    - pip

about:
  home: https://github.com/astral-sh/ruff-lsp
  summary: A Language Server Protocol implementation for Ruff.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berceanu
    - moritzwilksch
    - zanieb
