{% set name = "ruff-lsp" %}
{% set version = "0.0.62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ruff_lsp-{{ version }}.tar.gz
  sha256: 6db2a39375973ecb16c64d3c8dc37e23e1e191dcb7aebcf525b1f85ebd338c0d

build:
  entry_points:
    - ruff-lsp = ruff_lsp.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - packaging >=23.1
    - pygls >=1.1.0
    - lsprotocol >=2023.0.0a1
    - ruff >=0.0.274
    - typing-extensions

test:
  imports:
    - ruff_lsp
  commands:
    - pip check
    - ruff-lsp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/astral-sh/ruff-lsp
  summary: A Language Server Protocol implementation for Ruff.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhruvmanila
    - berceanu
    - moritzwilksch
    - zanieb
